// <auto-generated />
using System;
using Citel.Conecta.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Citel.Conecta.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260401203430_AdicionarNovasEntidadesHeartbeat")]
    partial class AdicionarNovasEntidadesHeartbeat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Citel.Conecta.Api.Models.AtividadeMonitoramento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ATV_CODPEN");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CodigoEntidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ATV_CODENT");

                    b.Property<string>("CodigoInterno")
                        .HasColumnType("longtext")
                        .HasColumnName("ATV_CODPLA");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ATV_DHUALT");

                    b.Property<string>("Erro")
                        .HasColumnType("longtext")
                        .HasColumnName("ATV_LOGERR");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ATV_NOMCLI");

                    b.Property<string>("NomeWorkflow")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ATV_NOMWFL");

                    b.Property<string>("Plataforma")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ATV_NOMPLA");

                    b.Property<string>("TipoEntidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ATV_TIPENT");

                    b.HasKey("Id");

                    b.ToTable("ATVPEN", (string)null);
                });

            modelBuilder.Entity("Citel.Conecta.Api.Models.ClienteMonitoramento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("CLI_CODPEN");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CodigoEntidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CLI_CODENT");

                    b.Property<string>("CodigoInterno")
                        .HasColumnType("longtext")
                        .HasColumnName("CLI_CODPLA");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CLI_DHUALT");

                    b.Property<string>("Erro")
                        .HasColumnType("longtext")
                        .HasColumnName("CLI_LOGERR");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CLI_NOMCLI");

                    b.Property<string>("NomeWorkflow")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CLI_NOMWFL");

                    b.Property<string>("Plataforma")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CLI_NOMPLA");

                    b.Property<string>("TipoEntidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CLI_TIPENT");

                    b.HasKey("Id");

                    b.ToTable("CLIPEN", (string)null);
                });

            modelBuilder.Entity("Citel.Conecta.Api.Models.CondicaoPagamentoMonitoramento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("CDP_CODPEN");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CodigoEntidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CDP_CODENT");

                    b.Property<string>("CodigoInterno")
                        .HasColumnType("longtext")
                        .HasColumnName("CDP_CODPLA");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CDP_DHUALT");

                    b.Property<string>("Erro")
                        .HasColumnType("longtext")
                        .HasColumnName("CDP_LOGERR");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CDP_NOMCLI");

                    b.Property<string>("NomeWorkflow")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CDP_NOMWFL");

                    b.Property<string>("Plataforma")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CDP_NOMPLA");

                    b.Property<string>("TipoEntidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CDP_TIPENT");

                    b.HasKey("Id");

                    b.ToTable("CDPPEN", (string)null);
                });

            modelBuilder.Entity("Citel.Conecta.Api.Models.CredencialMonitoramento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("CRD_CODPEN");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CodigoEntidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CRD_CODENT");

                    b.Property<string>("CodigoInterno")
                        .HasColumnType("longtext")
                        .HasColumnName("CRD_CODPLA");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CRD_DHUALT");

                    b.Property<string>("Erro")
                        .HasColumnType("longtext")
                        .HasColumnName("CRD_LOGERR");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CRD_NOMCLI");

                    b.Property<string>("NomeWorkflow")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CRD_NOMWFL");

                    b.Property<string>("Plataforma")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CRD_NOMPLA");

                    b.Property<string>("TipoEntidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CRD_TIPENT");

                    b.HasKey("Id");

                    b.ToTable("CRDPEN", (string)null);
                });

            modelBuilder.Entity("Citel.Conecta.Api.Models.EstoqueMonitoramento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("EST_CODPEN");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CodigoEntidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("EST_CODENT");

                    b.Property<string>("CodigoInterno")
                        .HasColumnType("longtext")
                        .HasColumnName("EST_CODPLA");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("EST_DHUALT");

                    b.Property<string>("Erro")
                        .HasColumnType("longtext")
                        .HasColumnName("EST_LOGERR");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("EST_NOMCLI");

                    b.Property<string>("NomeWorkflow")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("EST_NOMWFL");

                    b.Property<string>("Plataforma")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("EST_NOMPLA");

                    b.Property<string>("TipoEntidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("EST_TIPENT");

                    b.HasKey("Id");

                    b.ToTable("ESTPEN", (string)null);
                });

            modelBuilder.Entity("Citel.Conecta.Api.Models.Heartbeat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("HRT_CODPEN");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CicloEsperadoSegundos")
                        .HasColumnType("int")
                        .HasColumnName("HRT_CICSEG");

                    b.Property<int>("ItensProcessados")
                        .HasColumnType("int")
                        .HasColumnName("HRT_QTDPRO");

                    b.Property<string>("NomeWorkflow")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("HRT_NOMWFL");

                    b.Property<string>("TipoEntidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("HRT_TIPENT");

                    b.Property<DateTime>("UltimaExecucao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("HRT_DHUEXE");

                    b.Property<DateTime?>("UltimoSucesso")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("HRT_DHUSUC");

                    b.HasKey("Id");

                    b.ToTable("HRTBEN", (string)null);
                });

            modelBuilder.Entity("Citel.Conecta.Api.Models.LimiteCreditoMonitoramento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("LMC_CODPEN");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CodigoEntidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("LMC_CODENT");

                    b.Property<string>("CodigoInterno")
                        .HasColumnType("longtext")
                        .HasColumnName("LMC_CODPLA");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("LMC_DHUALT");

                    b.Property<string>("Erro")
                        .HasColumnType("longtext")
                        .HasColumnName("LMC_LOGERR");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("LMC_NOMCLI");

                    b.Property<string>("NomeWorkflow")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("LMC_NOMWFL");

                    b.Property<string>("Plataforma")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("LMC_NOMPLA");

                    b.Property<string>("TipoEntidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("LMC_TIPENT");

                    b.HasKey("Id");

                    b.ToTable("LMCPEN", (string)null);
                });

            modelBuilder.Entity("Citel.Conecta.Api.Models.NfeMonitoramento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("NFE_CODPEN");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CodigoEntidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("NFE_CODENT");

                    b.Property<string>("CodigoInterno")
                        .HasColumnType("longtext")
                        .HasColumnName("NFE_CODPLA");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("NFE_DHUALT");

                    b.Property<string>("Erro")
                        .HasColumnType("longtext")
                        .HasColumnName("NFE_LOGERR");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("NFE_NOMCLI");

                    b.Property<string>("NomeWorkflow")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("NFE_NOMWFL");

                    b.Property<string>("Plataforma")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("NFE_NOMPLA");

                    b.Property<string>("TipoEntidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("NFE_TIPENT");

                    b.HasKey("Id");

                    b.ToTable("NFEPEN", (string)null);
                });

            modelBuilder.Entity("Citel.Conecta.Api.Models.PedidoMonitoramento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("PED_CODPEN");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CodigoEntidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("PED_CODENT");

                    b.Property<string>("CodigoInterno")
                        .HasColumnType("longtext")
                        .HasColumnName("PED_CODPLA");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("PED_DHUALT");

                    b.Property<string>("Erro")
                        .HasColumnType("longtext")
                        .HasColumnName("PED_LOGERR");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("PED_NOMCLI");

                    b.Property<string>("NomeWorkflow")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("PED_NOMWFL");

                    b.Property<string>("Plataforma")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("PED_NOMPLA");

                    b.Property<string>("TipoEntidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("PED_TIPENT");

                    b.HasKey("Id");

                    b.ToTable("PEDPEN", (string)null);
                });

            modelBuilder.Entity("Citel.Conecta.Api.Models.PrecoMonitoramento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("PRC_CODPEN");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CodigoEntidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("PRC_CODENT");

                    b.Property<string>("CodigoInterno")
                        .HasColumnType("longtext")
                        .HasColumnName("PRC_CODPLA");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("PRC_DHUALT");

                    b.Property<string>("Erro")
                        .HasColumnType("longtext")
                        .HasColumnName("PRC_LOGERR");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("PRC_NOMCLI");

                    b.Property<string>("NomeWorkflow")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("PRC_NOMWFL");

                    b.Property<string>("Plataforma")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("PRC_NOMPLA");

                    b.Property<string>("TipoEntidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("PRC_TIPENT");

                    b.HasKey("Id");

                    b.ToTable("PRCPEN", (string)null);
                });

            modelBuilder.Entity("Citel.Conecta.Api.Models.ProdutoMonitoramento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("PRD_CODPEN");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CodigoEntidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("PRD_CODENT");

                    b.Property<string>("CodigoInterno")
                        .HasColumnType("longtext")
                        .HasColumnName("PRD_CODPLA");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("PRD_DHUALT");

                    b.Property<string>("Erro")
                        .HasColumnType("longtext")
                        .HasColumnName("PRD_LOGERR");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("PRD_NOMCLI");

                    b.Property<string>("NomeWorkflow")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("PRD_NOMWFL");

                    b.Property<string>("Plataforma")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("PRD_NOMPLA");

                    b.Property<string>("TipoEntidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("PRD_TIPENT");

                    b.HasKey("Id");

                    b.ToTable("PRDPEN", (string)null);
                });

            modelBuilder.Entity("Citel.Conecta.Api.Models.TabelaPrecoMonitoramento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("TBP_CODPEN");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CodigoEntidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TBP_CODENT");

                    b.Property<string>("CodigoInterno")
                        .HasColumnType("longtext")
                        .HasColumnName("TBP_CODPLA");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("TBP_DHUALT");

                    b.Property<string>("Erro")
                        .HasColumnType("longtext")
                        .HasColumnName("TBP_LOGERR");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TBP_NOMCLI");

                    b.Property<string>("NomeWorkflow")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TBP_NOMWFL");

                    b.Property<string>("Plataforma")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TBP_NOMPLA");

                    b.Property<string>("TipoEntidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TBP_TIPENT");

                    b.HasKey("Id");

                    b.ToTable("TBPPEN", (string)null);
                });

            modelBuilder.Entity("Citel.Conecta.Api.Models.TituloMonitoramento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("TTL_CODPEN");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CodigoEntidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TTL_CODENT");

                    b.Property<string>("CodigoInterno")
                        .HasColumnType("longtext")
                        .HasColumnName("TTL_CODPLA");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("TTL_DHUALT");

                    b.Property<string>("Erro")
                        .HasColumnType("longtext")
                        .HasColumnName("TTL_LOGERR");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TTL_NOMCLI");

                    b.Property<string>("NomeWorkflow")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TTL_NOMWFL");

                    b.Property<string>("Plataforma")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TTL_NOMPLA");

                    b.Property<string>("TipoEntidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TTL_TIPENT");

                    b.HasKey("Id");

                    b.ToTable("TTLPEN", (string)null);
                });

            modelBuilder.Entity("Citel.Conecta.Api.Models.TransportadoraMonitoramento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("TRA_CODPEN");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CodigoEntidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TRA_CODENT");

                    b.Property<string>("CodigoInterno")
                        .HasColumnType("longtext")
                        .HasColumnName("TRA_CODPLA");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("TRA_DHUALT");

                    b.Property<string>("Erro")
                        .HasColumnType("longtext")
                        .HasColumnName("TRA_LOGERR");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TRA_NOMCLI");

                    b.Property<string>("NomeWorkflow")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TRA_NOMWFL");

                    b.Property<string>("Plataforma")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TRA_NOMPLA");

                    b.Property<string>("TipoEntidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TRA_TIPENT");

                    b.HasKey("Id");

                    b.ToTable("TRAPEN", (string)null);
                });

            modelBuilder.Entity("Citel.Conecta.Api.Models.TributacaoMonitoramento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("TRB_CODPEN");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CodigoEntidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TRB_CODENT");

                    b.Property<string>("CodigoInterno")
                        .HasColumnType("longtext")
                        .HasColumnName("TRB_CODPLA");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("TRB_DHUALT");

                    b.Property<string>("Erro")
                        .HasColumnType("longtext")
                        .HasColumnName("TRB_LOGERR");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TRB_NOMCLI");

                    b.Property<string>("NomeWorkflow")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TRB_NOMWFL");

                    b.Property<string>("Plataforma")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TRB_NOMPLA");

                    b.Property<string>("TipoEntidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TRB_TIPENT");

                    b.HasKey("Id");

                    b.ToTable("TRBPEN", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
