// <auto-generated />
using System;
using Citel.Conecta.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Citel.Conecta.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260401201931_AdicionarNomeWorkflowTipoEntidade")]
    partial class AdicionarNomeWorkflowTipoEntidade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Citel.Conecta.Api.Models.ClienteMonitoramento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("CLI_CODPEN");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CodigoEntidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CLI_CODENT");

                    b.Property<string>("CodigoInterno")
                        .HasColumnType("longtext")
                        .HasColumnName("CLI_CODPLA");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CLI_DHUALT");

                    b.Property<string>("Erro")
                        .HasColumnType("longtext")
                        .HasColumnName("CLI_LOGERR");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CLI_NOMCLI");

                    b.Property<string>("NomeWorkflow")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CLI_NOMWFL");

                    b.Property<string>("Plataforma")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CLI_NOMPLA");

                    b.Property<string>("TipoEntidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CLI_TIPENT");

                    b.HasKey("Id");

                    b.ToTable("CLIPEN", (string)null);
                });

            modelBuilder.Entity("Citel.Conecta.Api.Models.TituloMonitoramento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("TTL_CODPEN");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CodigoEntidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TTL_CODENT");

                    b.Property<string>("CodigoInterno")
                        .HasColumnType("longtext")
                        .HasColumnName("TTL_CODPLA");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("TTL_DHUALT");

                    b.Property<string>("Erro")
                        .HasColumnType("longtext")
                        .HasColumnName("TTL_LOGERR");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TTL_NOMCLI");

                    b.Property<string>("NomeWorkflow")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TTL_NOMWFL");

                    b.Property<string>("Plataforma")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TTL_NOMPLA");

                    b.Property<string>("TipoEntidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TTL_TIPENT");

                    b.HasKey("Id");

                    b.ToTable("TTLPEN", (string)null);
                });

            modelBuilder.Entity("Citel.Conecta.Api.Models.TributacaoMonitoramento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("TRB_CODPEN");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CodigoEntidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TRB_CODENT");

                    b.Property<string>("CodigoInterno")
                        .HasColumnType("longtext")
                        .HasColumnName("TRB_CODPLA");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("TRB_DHUALT");

                    b.Property<string>("Erro")
                        .HasColumnType("longtext")
                        .HasColumnName("TRB_LOGERR");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TRB_NOMCLI");

                    b.Property<string>("NomeWorkflow")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TRB_NOMWFL");

                    b.Property<string>("Plataforma")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TRB_NOMPLA");

                    b.Property<string>("TipoEntidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TRB_TIPENT");

                    b.HasKey("Id");

                    b.ToTable("TRBPEN", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
